set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

set-option -g default-command "/usr/local/bin/zsh"

set-window-option -g mode-keys vi

set -g word-separators " |{}()[]<>`='\"!@#$%^&*:;,?"

bind r source-file ~/.tmux.conf

# clipboard
set -g set-clipboard on
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
set -g @yank_with_mouse off

# Start windows/panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Window titles
set-window-option -g automatic-rename on
set-option -g allow-rename on

set-option -g mouse on

# open panes in current directory
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind j resize-pane -D 5
bind k resize-pane -U 5
bind h resize-pane -L 15
bind l resize-pane -R 15

bind = select-layout even-horizontal

# smart pane switching with awareness of vim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
   | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n M-h if-shell "$is_vim" "send-keys ^[ :TmuxNavigateLeft Enter"  "select-pane -L"
bind-key -n M-j if-shell "$is_vim" "send-keys ^[ :TmuxNavigateDown Enter"  "select-pane -D"
bind-key -n M-k if-shell "$is_vim" "send-keys ^[ :TmuxNavigateUp Enter"  "select-pane -U"
bind-key -n M-l if-shell "$is_vim" "send-keys ^[ :TmuxNavigateRight Enter"  "select-pane -R"

# Don't confirm on pane/window kill
bind-key x kill-pane

# Sync panes
bind-key a setw synchronize-panes

# Theme stuff
set -g message-command-style "bg=colour19,fg=colour7"
set -g message-style "bg=colour19,fg=colour7"
setw -g window-status-activity-style "bg=colour18,fg=colour4,none"
setw -g window-status-style "bg=colour18,fg=colour7,none"
set -g status-style "none"
set -g status-left-style "none"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour4"
set -g pane-border-style "fg=colour19"
set -g status-bg "colour18"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "100"
setw -g window-status-separator ""
set -g status-left "#[fg=colour18,bg=colour4,bold] #S #[fg=colour4,bg=colour18]"
set -g status-right "#[fg=colour19,bg=colour18]#[default]#[fg=colour19]#[fg=colour7,bg=colour19] #[fg=colour4,bg=colour19]#[fg=colour18,bg=colour4,bold] %Y.%m.%d %H:%M "
# setw -g window-status-format "#[fg=colour7,bg=colour18] #I #[fg=colour7,bg=colour18] #W "
# setw -g window-status-current-format "#[fg=colour18,bg=colour19]#[fg=colour7,bg=colour19] #I #[fg=colour7,bg=colour19] #W #[fg=colour19,bg=colour18]"
setw -g window-status-format "#[fg=colour7,bg=colour18] #I #[fg=colour7,bg=colour18] #W "
setw -g window-status-current-format "#[fg=colour18,bg=colour19]#[fg=colour7,bg=colour19] #I #[fg=colour7,bg=colour19] #W #[fg=colour19,bg=colour18]"
set-option -g status-position bottom
