# Warning: This config does not include keys that have an unset value

# $all is shorthand for $username$hostname$localip$shlvl$singularity$kubernetes$nats$directory$vcsh$fossil_branch$fossil_metrics$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package$bun$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$gradle$haskell$haxe$helm$java$julia$kotlin$lua$mojo$nim$nodejs$ocaml$odin$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$typst$vlang$vagrant$zig$buf$guix_shell$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$direnv$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$container$os$shell$character
"$schema" = "https://starship.rs/config-schema.json"
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"
right_format = "$time"
continuation_prompt = "[∙](bright-black) "
scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

[time]
disabled = false
format = '[$time]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "red"
stashed = ''
ahead = "[⇡$count](yellow)"
behind = "[⇣$count](yellow)"
up_to_date = ""
diverged = "[⇡$ahead_count](yellow)[⇣$behind_count](yellow)"
conflicted = "!$count "
deleted = "-$count "
renamed = "»"
modified = "~$count "
staged = "[+$count](green) "
untracked = "+$count "
typechanged = ""
ignore_submodules = false
disabled = false
